name: build

on: [push, pull_request]

jobs:
    job1:
        name: Build
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Install ROS2 Humble 
              run: |
                  # Ref: https://index.ros.org/doc/ros2/Installation/humble/Linux-Install-Debians/
                  sudo locale-gen en_US en_US.UTF-8
                  sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
                  export LANG=en_US.UTF-8
                  sudo apt update && sudo apt install curl gnupg2 lsb-release
                  sudo apt install software-properties-common
                  sudo add-apt-repository universe
                  curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
                  sudo sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
                  sudo apt update
                  sudo apt install ros-humble-desktop
                  source /opt/ros/humble/setup.bash
            - name: Create Workspace
              run: |                  
                  mkdir -p ~/ros2_ws/src
                  cp -r $GITHUB_WORKSPACE/. ~/ros2_ws/src/Seek-Thermal-ROS2-Wrapper
            - name: Install Dependencies
              run: |
                  source /opt/ros/humble/setup.bash
                  sudo apt install python3-colcon-common-extensions
                  sudo apt install -y python3-rosdep2
                  sudo apt-get install git
                  sudo apt install -y python3-pip
                  sudo apt install -y python3-opencv
                  sudo pip3 install opencv-python
                  rosdep update
            - name: Install deb
              run: |             
                  sudo dpkg -i ~/ros2_ws/src/Seek-Thermal-ROS2-Wrapper/library/seekthermal-sdk-dev-4.3.1.6_amd64.deb
            - name: Build Packages
              run: |            
                  cd ~/ros2_ws
                  source /opt/ros/humble/setup.bash
                  rosdep update
                  rosdep install -y -r -q --from-paths src --ignore-src --rosdistro humble   
                  colcon build --symlink-install 
