name: build

on: [push, pull_request]

jobs:
    job1:
        name: Build
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Install ROS2 Foxy 
              run: |
                  # Ref: https://index.ros.org/doc/ros2/Installation/foxy/Linux-Install-Debians/
                  sudo locale-gen en_US en_US.UTF-8
                  sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
                  export LANG=en_US.UTF-8
                  sudo apt update && sudo apt install curl gnupg2 lsb-release
                  sudo apt install software-properties-common
                  sudo add-apt-repository universe
                  curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
                  sudo sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
                  sudo apt update
                  sudo apt install ros-foxy-desktop
                  source /opt/ros/foxy/setup.bash
            - name: Create Workspace
              run: |                  
                  mkdir -p ~/ros2_ws/
                  cp -a $GITHUB_WORKSPACE/. ~/ros2_ws/
            - name: Install Dependencies
              run: |
                  source /opt/ros/foxy/setup.bash
                  sudo apt install python3-colcon-common-extensions
                  sudo apt install -y python3-rosdep2
                  sudo apt-get install git
                  sudo apt install -y python3-pip
                  sudo apt install -y python3-opencv
                  sudo pip3 install opencv-python
                  rosdep update
            - name: Install deb
              run: |                  
                  cd ~/ros2_ws/library                  
                  sudo apt install -y ./seekthermal-sdk-dev-4.3.1.6_amd64.deb
            - name: Install seekcamera-python
              run: |                  
                  cd ~/ros2_ws/library/seekcamera-python
                  sudo pip3 install -e .
            - name: Build Packages
              run: |            
                  source /opt/ros/foxy/setup.bash
                  cd ~/ros2_ws/ros2_package
                  rosdep update
                  rosdep install -y -r -q --from-paths src --ignore-src --rosdistro foxy   
                  colcon build --symlink-install 
